### ISSUE TITLE
numpy/scipy versions

### ISSUE THREAD

**Issue by daler** [troublezhang/PePr#6]
Hi, 

Can you describe why older, specific versions of numpy==1.6.0 and scipy==0.14.0 are required? 

Long story short: the reason I ask is that I usually use [Anaconda](http://continuum.io/downloads) to create virtual environments on our cluster, but this combination of versions is not supported, e.g., 

```
conda install -n pepr-env numpy=1.6 scipy=0.14.0
Fetching package metadata: ..
Solving package specifications: ..
Error: Unsatisfiable package specifications.
Generating hint: 
[      COMPLETE      ] |################################################################################################| 100%


Hint: the following combinations of packages create a conflict with the
remaining packages:
  - scipy 0.14|0.14.0*
  - numpy 1.6*
```

**Comment by troublezhang** [comment]
Hi Ryan, 

These are the stable versions of packages that I'm using on my development server for PePr. I heard from people who were using other versions of Numpy and Scipy (mainly Scipy) that they had problems in the normalization step. Maybe I should set the version requirements to be numpy>=1.6.0 and scipy>=0.14.0. Do you think it would solve your problem?

Thanks,
Yanxiao

**Comment by daler** [comment]
Thanks, that would certainly solve my problem -- especially if the normalization issue noticed by others is due to older (rather than newer) scipy/numpy versions.

**Comment by troublezhang** [comment]
Most of the problems indeed come from older versions of scipy, but some with new versions have the same problems, too. I suspect those may be the memory problem but I could not confirm it. I'll keep watching on it. 

Try the new version and see if it will work. If it works for you, I'll close this ticket. Thanks!

**Comment by daler** [comment]
Sorry for the late reply -- allowing newer versions of NumPy and SciPy seems to work fine. Thanks.
